set(_CATKIN_CURRENT_PACKAGE "moveit_commander")
set(moveit_commander_VERSION "0.6.1")
set(moveit_commander_MAINTAINER "Ioan Sucan <isucan@willowgarage.com>")
set(moveit_commander_PACKAGE_FORMAT "1")
set(moveit_commander_BUILD_DEPENDS "moveit_ros_planning" "moveit_ros_planning_interface" "moveit_ros_warehouse" "moveit_ros_manipulation" "roscpp" "rospy" "rosconsole" "actionlib" "tf" "eigen_conversions" "python" "python-pyassimp")
set(moveit_commander_BUILD_EXPORT_DEPENDS "moveit_ros_planning" "moveit_ros_planning_interface" "moveit_ros_warehouse" "moveit_ros_manipulation" "roscpp" "rospy" "rosconsole" "actionlib" "tf" "eigen_conversions" "python" "python-pyassimp")
set(moveit_commander_BUILDTOOL_DEPENDS "catkin" "python-catkin-pkg")
set(moveit_commander_BUILDTOOL_EXPORT_DEPENDS )
set(moveit_commander_EXEC_DEPENDS "moveit_ros_planning" "moveit_ros_planning_interface" "moveit_ros_warehouse" "moveit_ros_manipulation" "roscpp" "rospy" "rosconsole" "actionlib" "tf" "eigen_conversions" "python" "python-pyassimp")
set(moveit_commander_RUN_DEPENDS "moveit_ros_planning" "moveit_ros_planning_interface" "moveit_ros_warehouse" "moveit_ros_manipulation" "roscpp" "rospy" "rosconsole" "actionlib" "tf" "eigen_conversions" "python" "python-pyassimp")
set(moveit_commander_TEST_DEPENDS )
set(moveit_commander_DOC_DEPENDS )
set(moveit_commander_DEPRECATED "")