set(_CATKIN_CURRENT_PACKAGE "srdfdom")
set(srdfdom_VERSION "0.3.0")
set(srdfdom_MAINTAINER "Ioan Sucan <isucan@willowgarage.com>")
set(srdfdom_PACKAGE_FORMAT "1")
set(srdfdom_BUILD_DEPENDS "boost" "libconsole-bridge-dev" "liburdfdom-headers-dev" "urdfdom_py" "tinyxml" "cmake_modules" "rostest")
set(srdfdom_BUILD_EXPORT_DEPENDS "boost" "libconsole-bridge-dev" "liburdfdom-headers-dev" "urdfdom_py" "tinyxml")
set(srdfdom_BUILDTOOL_DEPENDS "catkin" "pkg-config")
set(srdfdom_BUILDTOOL_EXPORT_DEPENDS )
set(srdfdom_EXEC_DEPENDS "boost" "libconsole-bridge-dev" "liburdfdom-headers-dev" "urdfdom_py" "tinyxml")
set(srdfdom_RUN_DEPENDS "boost" "libconsole-bridge-dev" "liburdfdom-headers-dev" "urdfdom_py" "tinyxml")
set(srdfdom_TEST_DEPENDS )
set(srdfdom_DOC_DEPENDS )
set(srdfdom_DEPRECATED "")