set(srdfdom_SETUP_PY_VERSION "0.3.0")
set(srdfdom_SETUP_PY_SCRIPTS "")
set(srdfdom_SETUP_PY_PACKAGES "srdfdom")
set(srdfdom_SETUP_PY_PACKAGE_DIRS "src/srdfdom")
set(srdfdom_SETUP_PY_MODULES "")
set(srdfdom_SETUP_PY_MODULE_DIRS "")