set(_CATKIN_CURRENT_PACKAGE "moveit_setup_assistant")
set(moveit_setup_assistant_VERSION "0.7.1")
set(moveit_setup_assistant_MAINTAINER "Ioan Sucan <isucan@gmail.com>, Dave Coleman <davetcoleman@gmail.com>")
set(moveit_setup_assistant_PACKAGE_FORMAT "1")
set(moveit_setup_assistant_BUILD_DEPENDS "moveit_core" "moveit_ros_planning" "moveit_ros_visualization" "yaml-cpp")
set(moveit_setup_assistant_BUILD_EXPORT_DEPENDS "moveit_core" "moveit_ros_planning" "moveit_ros_visualization" "yaml-cpp" "xacro")
set(moveit_setup_assistant_BUILDTOOL_DEPENDS "catkin")
set(moveit_setup_assistant_BUILDTOOL_EXPORT_DEPENDS )
set(moveit_setup_assistant_EXEC_DEPENDS "moveit_core" "moveit_ros_planning" "moveit_ros_visualization" "yaml-cpp" "xacro")
set(moveit_setup_assistant_RUN_DEPENDS "moveit_core" "moveit_ros_planning" "moveit_ros_visualization" "yaml-cpp" "xacro")
set(moveit_setup_assistant_TEST_DEPENDS )
set(moveit_setup_assistant_DOC_DEPENDS )
set(moveit_setup_assistant_DEPRECATED "")