#!/usr/bin/env sh
# generated from catkin/python/catkin/environment_cache.py

# based on a snapshot of the environment before and after calling the setup script
# it emulates the modifications of the setup script without recurring computations

# new environment variables

# modified environment variables
export CMAKE_PREFIX_PATH="/home/donghoonpark/moveit/devel_isolated/moveit_ros_manipulation:$CMAKE_PREFIX_PATH"
export LD_LIBRARY_PATH="/opt/ros/kinetic/lib/x86_64-linux-gnu:/home/donghoonpark/moveit/devel_isolated/moveit_ros_move_group/lib:/home/donghoonpark/moveit/devel_isolated/moveit_planners_ompl/lib:/home/donghoonpark/moveit/devel_isolated/moveit_fake_controller_manager/lib:/home/donghoonpark/moveit/devel_isolated/moveit_ros_planning/lib:/home/donghoonpark/moveit/devel_isolated/moveit_ros_perception/lib:/home/donghoonpark/moveit/devel_isolated/moveit_controller_manager_example/lib:/home/donghoonpark/moveit/devel_isolated/moveit_core/lib:/home/donghoonpark/moveit/devel_isolated/srdfdom/lib:/home/donghoonpark/moveit/devel_isolated/moveit_resources/lib:/home/donghoonpark/moveit/devel_isolated/moveit_msgs/lib:/home/donghoonpark/moveit/devel_isolated/manipulation_msgs/lib:/home/donghoonpark/moveit/devel_isolated/household_objects_database_msgs/lib:/home/donghoonpark/moveit/install/lib:/home/donghoonpark/catkin_workspace/devel/lib:/home/donghoonpark/moveit/devel/lib:/home/donghoonpark/catkin_workspace/install/lib:/opt/ros/kinetic/lib"
export PKG_CONFIG_PATH="/opt/ros/kinetic/lib/x86_64-linux-gnu/pkgconfig:/home/donghoonpark/moveit/devel_isolated/moveit_ros_move_group/lib/pkgconfig:/home/donghoonpark/moveit/devel_isolated/moveit_planners_ompl/lib/pkgconfig:/home/donghoonpark/moveit/devel_isolated/moveit_fake_controller_manager/lib/pkgconfig:/home/donghoonpark/moveit/devel_isolated/moveit_ros_planning/lib/pkgconfig:/home/donghoonpark/moveit/devel_isolated/moveit_ros_perception/lib/pkgconfig:/home/donghoonpark/moveit/devel_isolated/moveit_controller_manager_example/lib/pkgconfig:/home/donghoonpark/moveit/devel_isolated/moveit_core/lib/pkgconfig:/home/donghoonpark/moveit/devel_isolated/srdfdom/lib/pkgconfig:/home/donghoonpark/moveit/devel_isolated/moveit_resources/lib/pkgconfig:/home/donghoonpark/moveit/devel_isolated/moveit_msgs/lib/pkgconfig:/home/donghoonpark/moveit/devel_isolated/manipulation_msgs/lib/pkgconfig:/home/donghoonpark/moveit/devel_isolated/household_objects_database_msgs/lib/pkgconfig:/home/donghoonpark/moveit/install/lib/pkgconfig:/home/donghoonpark/catkin_workspace/devel/lib/pkgconfig:/home/donghoonpark/moveit/devel/lib/pkgconfig:/home/donghoonpark/catkin_workspace/install/lib/pkgconfig:/opt/ros/kinetic/lib/pkgconfig"
export ROSLISP_PACKAGE_DIRECTORIES="/home/donghoonpark/moveit/devel_isolated/moveit_ros_manipulation/share/common-lisp:$ROSLISP_PACKAGE_DIRECTORIES"
export ROS_PACKAGE_PATH="/home/donghoonpark/moveit/src/moveit_ros/manipulation:$ROS_PACKAGE_PATH"