set(_CATKIN_CURRENT_PACKAGE "moveit_msgs")
set(moveit_msgs_VERSION "0.8.1")
set(moveit_msgs_MAINTAINER "Ioan Sucan <isucan@google.com>")
set(moveit_msgs_PACKAGE_FORMAT "1")
set(moveit_msgs_BUILD_DEPENDS "message_generation" "octomap_msgs" "actionlib_msgs" "sensor_msgs" "geometry_msgs" "trajectory_msgs" "shape_msgs" "object_recognition_msgs" "std_msgs")
set(moveit_msgs_BUILD_EXPORT_DEPENDS "message_runtime" "octomap_msgs" "actionlib_msgs" "sensor_msgs" "geometry_msgs" "trajectory_msgs" "shape_msgs" "object_recognition_msgs" "std_msgs")
set(moveit_msgs_BUILDTOOL_DEPENDS "catkin")
set(moveit_msgs_BUILDTOOL_EXPORT_DEPENDS )
set(moveit_msgs_EXEC_DEPENDS "message_runtime" "octomap_msgs" "actionlib_msgs" "sensor_msgs" "geometry_msgs" "trajectory_msgs" "shape_msgs" "object_recognition_msgs" "std_msgs")
set(moveit_msgs_RUN_DEPENDS "message_runtime" "octomap_msgs" "actionlib_msgs" "sensor_msgs" "geometry_msgs" "trajectory_msgs" "shape_msgs" "object_recognition_msgs" "std_msgs")
set(moveit_msgs_TEST_DEPENDS )
set(moveit_msgs_DOC_DEPENDS )
set(moveit_msgs_DEPRECATED "")